"""initial schema

Revision ID: 4663fd393f70
Revises: 
Create Date: 2026-07-21 23:54:26.519924
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4663fd393f70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempt_principal_time', 'login_attempts', ['username', 'ip_address', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks'))
    )
    op.create_index(op.f('ix_scheduled_tasks_scheduled_for'), 'scheduled_tasks', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_status'), 'scheduled_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_task_type'), 'scheduled_tasks', ['task_type'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(length=512), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vpngate_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('host_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('ping_ms', sa.Integer(), nullable=True),
    sa.Column('speed_bps', sa.Integer(), nullable=True),
    sa.Column('country_long', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('total_traffic_bytes', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('remote_port', sa.Integer(), nullable=False),
    sa.Column('sanitized_config', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('asn_organization', sa.String(length=255), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('ptr', sa.String(length=255), nullable=True),
    sa.Column('network_type', sa.String(length=32), nullable=False),
    sa.Column('network_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vpngate_nodes'))
    )
    op.create_index(op.f('ix_vpngate_nodes_config_hash'), 'vpngate_nodes', ['config_hash'], unique=True)
    op.create_index(op.f('ix_vpngate_nodes_country_code'), 'vpngate_nodes', ['country_code'], unique=False)
    op.create_index(op.f('ix_vpngate_nodes_ip_address'), 'vpngate_nodes', ['ip_address'], unique=False)
    op.create_index(op.f('ix_vpngate_nodes_is_available'), 'vpngate_nodes', ['is_available'], unique=False)
    op.create_index(op.f('ix_vpngate_nodes_last_seen_at'), 'vpngate_nodes', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_vpngate_nodes_network_type'), 'vpngate_nodes', ['network_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('blocked_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_blocked_nodes_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['vpngate_nodes.id'], name=op.f('fk_blocked_nodes_node_id_vpngate_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocked_nodes')),
    sa.UniqueConstraint('config_hash', name=op.f('uq_blocked_nodes_config_hash')),
    sa.UniqueConstraint('node_id', name=op.f('uq_blocked_nodes_node_id'))
    )
    op.create_table('node_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('exit_ip', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['vpngate_nodes.id'], name=op.f('fk_node_scan_results_node_id_vpngate_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_scan_results'))
    )
    op.create_index('ix_node_scan_node_created', 'node_scan_results', ['node_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_node_scan_results_node_id'), 'node_scan_results', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_scan_results_status'), 'node_scan_results', ['status'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('vpn_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('veth_host', sa.String(length=32), nullable=False),
    sa.Column('veth_namespace', sa.String(length=32), nullable=False),
    sa.Column('subnet_cidr', sa.String(length=64), nullable=False),
    sa.Column('tun_device', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('exit_ip', sa.String(length=64), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('auto_switch_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['vpngate_nodes.id'], name=op.f('fk_vpn_connections_node_id_vpngate_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vpn_connections')),
    sa.UniqueConstraint('name', name=op.f('uq_vpn_connections_name')),
    sa.UniqueConstraint('subnet_cidr', name=op.f('uq_vpn_connections_subnet_cidr')),
    sa.UniqueConstraint('veth_host', name=op.f('uq_vpn_connections_veth_host')),
    sa.UniqueConstraint('veth_namespace', name=op.f('uq_vpn_connections_veth_namespace'))
    )
    op.create_index(op.f('ix_vpn_connections_namespace'), 'vpn_connections', ['namespace'], unique=True)
    op.create_index(op.f('ix_vpn_connections_node_id'), 'vpn_connections', ['node_id'], unique=False)
    op.create_index(op.f('ix_vpn_connections_status'), 'vpn_connections', ['status'], unique=False)
    op.create_table('connection_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['vpn_connections.id'], name=op.f('fk_connection_events_connection_id_vpn_connections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_events'))
    )
    op.create_index(op.f('ix_connection_events_connection_id'), 'connection_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connection_events_created_at'), 'connection_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_connection_events_event_type'), 'connection_events', ['event_type'], unique=False)
    op.create_table('service_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['vpn_connections.id'], name=op.f('fk_service_checks_connection_id_vpn_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_checks'))
    )
    op.create_index('ix_service_check_connection_service', 'service_checks', ['connection_id', 'service_name'], unique=False)
    op.create_index(op.f('ix_service_checks_checked_at'), 'service_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_service_checks_connection_id'), 'service_checks', ['connection_id'], unique=False)
    op.create_index(op.f('ix_service_checks_service_name'), 'service_checks', ['service_name'], unique=False)
    op.create_index(op.f('ix_service_checks_status'), 'service_checks', ['status'], unique=False)
    op.create_table('socks_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('bind_address', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('client_ip_allowlist', sa.JSON(), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bytes_up', sa.Integer(), nullable=False),
    sa.Column('bytes_down', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['vpn_connections.id'], name=op.f('fk_socks_endpoints_connection_id_vpn_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_socks_endpoints'))
    )
    op.create_index(op.f('ix_socks_endpoints_connection_id'), 'socks_endpoints', ['connection_id'], unique=True)
    op.create_index(op.f('ix_socks_endpoints_is_active'), 'socks_endpoints', ['is_active'], unique=False)
    op.create_index(op.f('ix_socks_endpoints_port'), 'socks_endpoints', ['port'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socks_endpoints_port'), table_name='socks_endpoints')
    op.drop_index(op.f('ix_socks_endpoints_is_active'), table_name='socks_endpoints')
    op.drop_index(op.f('ix_socks_endpoints_connection_id'), table_name='socks_endpoints')
    op.drop_table('socks_endpoints')
    op.drop_index(op.f('ix_service_checks_status'), table_name='service_checks')
    op.drop_index(op.f('ix_service_checks_service_name'), table_name='service_checks')
    op.drop_index(op.f('ix_service_checks_connection_id'), table_name='service_checks')
    op.drop_index(op.f('ix_service_checks_checked_at'), table_name='service_checks')
    op.drop_index('ix_service_check_connection_service', table_name='service_checks')
    op.drop_table('service_checks')
    op.drop_index(op.f('ix_connection_events_event_type'), table_name='connection_events')
    op.drop_index(op.f('ix_connection_events_created_at'), table_name='connection_events')
    op.drop_index(op.f('ix_connection_events_connection_id'), table_name='connection_events')
    op.drop_table('connection_events')
    op.drop_index(op.f('ix_vpn_connections_status'), table_name='vpn_connections')
    op.drop_index(op.f('ix_vpn_connections_node_id'), table_name='vpn_connections')
    op.drop_index(op.f('ix_vpn_connections_namespace'), table_name='vpn_connections')
    op.drop_table('vpn_connections')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_node_scan_results_status'), table_name='node_scan_results')
    op.drop_index(op.f('ix_node_scan_results_node_id'), table_name='node_scan_results')
    op.drop_index('ix_node_scan_node_created', table_name='node_scan_results')
    op.drop_table('node_scan_results')
    op.drop_table('blocked_nodes')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vpngate_nodes_network_type'), table_name='vpngate_nodes')
    op.drop_index(op.f('ix_vpngate_nodes_last_seen_at'), table_name='vpngate_nodes')
    op.drop_index(op.f('ix_vpngate_nodes_is_available'), table_name='vpngate_nodes')
    op.drop_index(op.f('ix_vpngate_nodes_ip_address'), table_name='vpngate_nodes')
    op.drop_index(op.f('ix_vpngate_nodes_country_code'), table_name='vpngate_nodes')
    op.drop_index(op.f('ix_vpngate_nodes_config_hash'), table_name='vpngate_nodes')
    op.drop_table('vpngate_nodes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_scheduled_tasks_task_type'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_status'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_scheduled_for'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index('ix_login_attempt_principal_time', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###

